!     SUBROUTINES IN THIS FILE   CALLED FROM
!     subroutine monthly         main

!&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

subroutine monthly(mo1)
!**** CALLED IN MAIN
!**** THIS SUBROUTINE COMPUTES ONE DAY
!****
!**** CALLED:   IN MAIN
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!     PARAMETERS & VARIABLES
!   
!     ida         - current day
!     ieap      - index for GRASS output in subbasin (yield)
!     ieapu      - index for GRASS output in subbasin (annual sums)
!     xxswind      - soil water index for basin
!     xwysb      - water yield for basin
!     xnflow()   - N flows for a chosen hydrotop
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   use common_par
   use mod_reservoir !#### RESERVOIR MODULE ####
   use mod_snow      !#### SNOW MODULE      ####
   implicit none
   integer mo1, numunt 
   integer ii, iik, j, k, y
   integer inum1, inum2, inum3, inum4
   integer rnum1, idum
   integer icode, icodep, ihout
   logical :: bRoute = .true. !#### RESERVOIR MODULE ####

!ls** compute number of  days of the month
   if (mo1.eq.2) then
     inday = nc(mo1+1) - nc(mo1) - nt
   else
     inday = nc(mo1+1) - nc(mo1)
   endif

   do 520 iday = 1, inday

!ls** compute day number in the year
      if (mo1.gt.2) then
        ida = iday + nc(mo1) - nt
      else
        ida = iday + nc(mo1)
      endif

      area_tot_snow  = 0.
      depth_ave_snow = 0.
      !###########################
      !#### SNOW MODULE    ####
      !###########################
      if ( bSnowModule ) then
         ieapg = 1
         area_tot_glacier  = 0.
         depth_ave_glacier = 0.
      end if
      !###########################

      if (mod(ida,30).eq.0) write(6,1020)ida,mo,iy
      xxswind = 0.
      xwysb = 0.
      ieap  = 1
      ieapu = 1
      do ii=1,20
         xnflow(ii) = 0.
      end do
      do k = 1, nsb
         sub(k) = 0.
      end do

!####   CALL CLIREAD - to read climate data daily
      call readcli
!### VA
!***********  For Radiation Data generated by Hargreaves Samani
      if (radiation_switch > 0) call hargreaves_rad
!### VA

!ls     ndmo(mo) = ndmo(mo) + 1
!ls     dtot = dtot + 1.
      snoev = 0.
      pr = 0.

!########################################################### START ROUTING  
!####   CALL subbasin, route, transfer, add
      do idum = 1, mhyd
         icode = icodes(idum)
         ihout = ihouts(idum)
         inum1 = inum1s(idum)
         inum2 = inum2s(idum)
         if (icode.gt.0) then
            select case (icode)
               case (1)      ! SUBBASIN command
               !###########################
               !#### RESERVOIR MODULE ####
               !###########################
               if ( bRsvModule ) then
                  ! if actual subbasin is reservoir skip subbasin call
                  ! TODO: include res_active function
                  if ( rsvSubbasin(inum1) == 0 ) then
                     if (subcatch_id(inum1).ne.0) call subbasin(icode,ihout,inum1,inum2)
                  else
                     if (RSV_is_operational(iyr,ida,inum1) ) then
                        call RSV_subbasin(ihout,inum1,inum2)
                     else if (subcatch_id(inum1).ne.0) then
                        call subbasin(icode, ihout, inum1,inum2)
                     end if
                  end if
               ! calculate subbasin but only if subbasin is listed in subcatch.def
               ! for convenient subsetting of model eg. by subcatchment
               else if (subcatch_id(inum1).ne.0) then
                  call subbasin(icode, ihout, inum1,inum2)
               end if
              !###########################

               case (2)      ! ROUTE command
               bRoute = .true.
               !###########################
               !#### RESERVOIR MODULE ####
               !###########################
               if ( bRsvModule ) then
                  ! If inum1 is a reservoir subbasin then...
                  if ( bRsvHydrograph(ihout) ) then
                  ! reservoir input is stored in varoute(2,inum2) and varoute(8,inum2)
                  ! skip routing
                  ! modify varoute(2,inum1), varoute(8,inum1) in reservoir functions
                  ! DO NOT call route(icode,ihout,inum1,inum2)
                     if (RSV_is_operational(iyr,ida,inum1) ) then
                        call RSV_Reservoir_processes(ihout,inum1,inum2)
                        bRoute = .false.
                     end if
                  else
                     bRoute = .true.
                     !call route(icode, ihout, inum1,inum2)
                  end if
               end if
               !###########################

               if ( bRoute ) call route(icode, ihout, inum1,inum2)

               case (3) ! not implemented
               ! do nothing

               case (4) ! not implemented
                  ihout  = ihouts (idum - 1)
                  icodep = icodes (idum - 1)
                  call transfer(icode, ihout, inum1,inum2) ! not implemented

               case (5)      ! ADD command
               call add(icode, ihout, inum1,inum2)

               case default ! do nothing
            end select
         end if ! (icode.gt.0)
      end do ! do idum = 1, mhyd
!########################################################### END ROUTING   

!****   Calc wy - water yield 
      wy = sub(8) + sub(9) - sub(10) + sub(15) + 1.e-20

!****   Correction - sediment yield
      sub(21) = sub(21) / da9

!****   Calculation of monthly sums       
      do iik = 1, nvsub
         smm(iik) = smm(iik) + sub(iik)
      end do

!****   Calc monthly water discharge
      accf(7) = accf(7) + runo(ida,1)
      accf(8) = accf(8) + runs(ida)     

!####   CALL DAILY WRITE
      call wr_daily
      sub = 0.

  520 continue 
!     ############# DAILY LOOP CYCLE ########################

! SL begin
!****     write monthly discharge for reaches (rch1 - rch6)
!      write(170,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(1)
!      write(171,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(2)
!      write(172,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(3)
!      write(173,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(4)
!      write(174,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(5)
!      write(175,fmt='(2i4,f16.4)') iyr,mo1,runrchmon(6)
!      runrchmon = 0.
! 
      write(181,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(1,y),y=1,9)
      write(182,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(2,y),y=1,9)
      write(183,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(3,y),y=1,9)
      write(184,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(4,y),y=1,9)
      write(185,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(5,y),y=1,9)
      write(186,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(6,y),y=1,9)
      write(187,fmt='(2i6,9f12.2)') iyr,mo1,(htpmon(7,y),y=1,9)
      htpmon = 0.
! SL end

 1020 format('*** Day = ',i3,' Mon = ',i2,' Year = ',i5)
 9998 format (' ')

   return
end subroutine monthly
